# Name of the domain bridge, used for node naming and logging
name: my_bridge

# to_domain: 0

topics:

# pinky

# task_status topics ----------------------------

  task_status:
    type: std_msgs/msg/String
    from_domain: 31
    to_domain: 0
    remap: robot1/task_status

  task_status:
    type: std_msgs/msg/String
    from_domain: 32
    to_domain: 0
    remap: robot2/task_status

  task_status:
    type: std_msgs/msg/String
    from_domain: 33
    to_domain: 0
    remap: robot3/task_status

  task_status:
    type: std_msgs/msg/String
    from_domain: 34
    to_domain: 0
    remap: robot4/task_status

  task_status:
    type: std_msgs/msg/String
    from_domain: 35
    to_domain: 0
    remap: robot5/task_status

# battery topics --------------------------------
  pinky_battery_present:
    type: std_msgs/msg/Float32
    from_domain: 31
    to_domain: 0
    remap: robot1/battery

  pinky_battery_present:
    type: std_msgs/msg/Float32
    from_domain: 32
    to_domain: 0
    remap: robot2/battery

  pinky_battery_present:
    type: std_msgs/msg/Float32
    from_domain: 33
    to_domain: 0
    remap: robot3/battery

# camera_pose topics ----------------------------
  robot1/camera_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 0
    to_domain: 31
    remap: camera_pose

  robot2/camera_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 0
    to_domain: 32
    remap: camera_pose

  robot3/camera_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 0
    to_domain: 33
    remap: camera_pose

# cmd_vel topics ----------------------------
  # robot1/cmd_vel:
  #   type: geometry_msgs/msg/Twist
  #   from_domain: 0
  #   to_domain: 31
  #   remap: cmd_vel

  # robot2/cmd_vel:
  #   type: geometry_msgs/msg/Twist
  #   from_domain: 0
  #   to_domain: 32
  #   remap: cmd_vel

  # robot3/cmd_vel:
  #   type: geometry_msgs/msg/Twist
  #   from_domain: 0
  #   to_domain: 33
  #   remap: cmd_vel

  cmd_vel:
    type: geometry_msgs/msg/Twist
    from_domain: 31
    to_domain: 0
    remap: robot1/cmd_vel

  cmd_vel:
    type: geometry_msgs/msg/Twist
    from_domain: 32
    to_domain: 0
    remap: robot2/cmd_vel

  cmd_vel:
    type: geometry_msgs/msg/Twist
    from_domain: 33
    to_domain: 0
    remap: robot3/cmd_vel


# target_pose pub topics ----------------------------

  robot1/target_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 0
    to_domain: 31
    remap: target_pose

  robot2/target_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 0
    to_domain: 32
    remap: target_pose

  robot3/target_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 0
    to_domain: 33
    remap: target_pose
    
# target_pose sub topics ---------------------------
  target_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 0
    to_domain: 31
    remap: robot1/target_pose

  target_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 0
    to_domain: 32
    remap: robot2/target_pose

  target_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 0
    to_domain: 33
    remap: robot3/target_pose



# 로봇팔
  joint_states:
    type: sensor_msgs/msg/JointState
    from_domain: 34
    to_domain: 0
    remap: robot4/joint_states

  joint_states:
    type: sensor_msgs/msg/JointState
    from_domain: 35
    to_domain: 0
    remap: robot5/joint_states


# task pub topics 전체 ----------------------------

  robot1/task:
    type: bolt_fms/msg/TaskSimple
    from_domain: 0
    to_domain: 31
    remap: task

  robot2/task:
    type: bolt_fms/msg/TaskSimple
    from_domain: 0
    to_domain: 32
    remap: task

  robot3/task:
    type: bolt_fms/msg/TaskSimple
    from_domain: 0
    to_domain: 33
    remap: task

  robot4/task:
    type: bolt_fms/msg/TaskSimple
    from_domain: 0
    to_domain: 34
    remap: task

  robot5/task:
    type: bolt_fms/msg/TaskSimple
    from_domain: 0
    to_domain: 35
    remap: task