# Name of the domain bridge, used for node naming and logging
name: my_bridge

from_domain: 0

topics:

# camera_pose topics ----------------------------
  robot1/camera_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 0
    to_domain: 151
    remap: camera_pose

  robot2/camera_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 0
    to_domain: 33
    remap: camera_pose

  robot3/camera_pose:
    type: geometry_msgs/msg/PoseStamped
    # from_domain: 0
    # to_domain: 33
    remap: camera_pose


# target_pose topics ----------------------------

  robot1/target_pose:
    type: geometry_msgs/msg/PoseStamped
    # from_domain: 0
    to_domain: 151
    remap: target_pose

  robot2/target_pose:
    type: geometry_msgs/msg/PoseStamped
    # from_domain: 0
    to_domain: 33
    remap: target_pose

  robot3/target_pose:
    type: geometry_msgs/msg/PoseStamped
    # from_domain: 0
    # to_domain: 33
    remap: target_pose

  

  # pinky_battery_present:
  #   type: std_msgs/msg/String
  #   from_domain: 33
  #   to_domain: 100