# Name of the domain bridge, used for node naming and logging
name: my_bridge

from_domain: 0

topics:
  robot4/camera_pose:
    type: geometry_msgs/msg/PoseStamped
    # from_domain: 0
    to_domain: 151
    remap: camera_pose

  robot2/camera_pose:
    type: geometry_msgs/msg/PoseStamped
    # from_domain: 0
    to_domain: 33
    remap: camera_pose

  

  # pinky_battery_present:
  #   type: std_msgs/msg/String
  #   from_domain: 33
  #   to_domain: 100